fix(core): Do not crash on ASCII message of length 1 without `\r`
If the server sends an ASCII message that does not contain `\r`,
`result.lastIndexOf("\r")` will return `-1`. In case the entire message
only contains a single byte, this will be equal to `result.length() - 2`
and therefore load to the following crash:

    java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 1
            at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
            at java.base/java.lang.String.substring(String.java:1874)
            at de.rub.nds.sshattacker.core.protocol.transport.parser.AsciiMessageParser.parseText(AsciiMessageParser.java:38)
            at de.rub.nds.sshattacker.core.protocol.transport.parser.AsciiMessageParser.parseProtocolMessageContents(AsciiMessageParser.java:49)
            at de.rub.nds.sshattacker.core.protocol.common.ProtocolMessageParser.parse(ProtocolMessageParser.java:43)
            at de.rub.nds.sshattacker.core.protocol.common.ProtocolMessageParser.delegateParsing(ProtocolMessageParser.java:69)
            at de.rub.nds.sshattacker.core.protocol.common.layer.MessageLayer.parse(MessageLayer.java:28)
            at de.rub.nds.sshattacker.core.workflow.action.executor.ReceiveMessageHelper.handleReceivedBytes(ReceiveMessageHelper.java:137)
            at de.rub.nds.sshattacker.core.workflow.action.executor.ReceiveMessageHelper.receiveMessages(ReceiveMessageHelper.java:59)
            at de.rub.nds.sshattacker.core.workflow.action.ReceiveAction.execute(ReceiveAction.java:241)
            at de.rub.nds.sshattacker.core.workflow.DefaultWorkflowExecutor.executeWorkflow(DefaultWorkflowExecutor.java:59)

Also, if the message is malformed and does not end with a newline
character, the end-of-message sequence would be wrong. This edge case is
also fixed here.